### PR TITLE
Adding Export, fixing static libraries and binaries

### PR DESCRIPTION
**Pull request by msoos**

### CODE REVIEW

**Comment by ccadar** [comment]
@msoos KLEE fails with the recent changes to this repo, so I'm wondering if you can provide a short summary of what has changed.  What options do I need to pass to get the same behaviour as 2 days ago?  Many thanks!

**Comment by msoos** [comment]
Ayyy. OK, let me try to build KLEE and see how I broke it. Sorry.

**Comment by ccadar** [comment]
Thanks for the quick response.  You can see a recent run here, where KLEE with STP master fails:
https://github.com/klee/klee/pull/1299/checks?check_run_id=1062667139

We get the error message `/usr/bin/ld: cannot find -lminisat` so perhaps we just need to add a `-L` flag somewhere, but I was a bit confused about what changed.

**Comment by msoos** [comment]
Thanks for the detailed error log, I'm working on it!

**Comment by msoos** [comment]
Thank you again for your quick response. I think I now fixed it! Can you please check? Again, sorry for breaking the build.

**Comment by ccadar** [comment]
@msoos this did it!  Really appreciate the super quick fix!!

**Pull request merged**
