### PR TITLE
utils/System.*: use fpu_control only on glibc

### PR DESCRIPTION
**Pull request by xgqt**
Bug: https://github.com/vprover/vampire/pull/432
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

### CODE REVIEW

**Comment by rgov** [comment]
Thanks! @msoos any comment? I think it makes sense because this header is specific to Glibc: https://www.gnu.org/software/gnulib/manual/html_node/fpu_005fcontrol_002eh.html

**Comment by xgqt** [comment]
See also: https://github.com/vprover/vampire/pull/432

**Comment by xgqt** [comment]
And also: https://github.com/usi-verification-and-security/opensmt/pull/590

**Review by msoos — APPROVED** [review]
Looks good to me!

**Comment by msoos** [comment]
@rgov Thanks for pinging me. Since both you and me agree it makes sense, I merged it :) I hope that's OK!

**Pull request merged**
